
name: Build Tailscale
on:
  # push:
  workflow_dispatch:
    inputs:
      sdkURL:
        description: 'sdk地址'
        required: true
        default: 'https://github.com/mjl371/Actions-immortalwrt-mt7981/releases/download/sdk/immortalwrt-sdk-mediatek-mt7981_gcc-8.4.0_musl.Linux-x86_64.tar.xz'
        type: input
          
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev file wget jq
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Use Sdk
      working-directory: /workdir
      run: |
        wget "${{ inputs.sdkURL }}"
        tar -xf *.tar.xz 
        mv $(basename "${{ inputs.sdkURL }}"| sed 's/.\{7\}$//' ) openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        
    - name: Update feeds
      run: |
        cd openwrt 
        sed -i '3,5d' feeds.conf.default
        ./scripts/feeds update -a

    - name: Update Tailsclae
      if:  ${{ inputs.tailscaleBranch }}!= 'none'
      run: |
      
        git clone -b master https://github.com/openwrt/packages.git
  
        rm -rf openwrt/feeds/packages/lang/golang
        cp -r packages/lang/golang openwrt/feeds/packages/lang/golang
        
        rm -rf openwrt/feeds/packages/net/tailscale
        cp -r packages/net/tailscale openwrt/feeds/packages/net/tailscale
        
        # git clone https://github.com/mjl371/Actions-immortalwrt-mt7981.git
        # mv -f Actions-immortalwrt-mt7981/tailscale/Makefile openwrt/feeds/packages/net/tailscale/Makefile
        # grep PKG_VERSION:= openwrt/feeds/packages/net/tailscale/Makefile |awk -F ':=' '{print $2}' > TAILSCALE_VERSION
        
        curl -s https://api.github.com/repos/tailscale/tailscale/releases/latest |jq -r '.tag_name' |sed 's/v//' > TAILSCALE_VERSION
        echo "TAILSCALE_VERSION=$(cat TAILSCALE_VERSION)" >> $GITHUB_ENV
        cat TAILSCALE_VERSION
        wget -O tailscale.latest  "https://codeload.github.com/tailscale/tailscale/tar.gz/v$(cat TAILSCALE_VERSION)"
        sha256sum tailscale.latest |awk '{print $1}' > PKGHASH
        cat PKGHASH
        sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=$(cat TAILSCALE_VERSION)/" openwrt/feeds/packages/net/tailscale/Makefile
        sed -i "s/PKG_HASH:=.*/PKG_HASH:=$(cat PKGHASH)/" openwrt/feeds/packages/net/tailscale/Makefile

        cat openwrt/feeds/packages/net/tailscale/Makefile
        
        sed -i '$ s/nftables/iptables/' openwrt/feeds/packages/net/tailscale/files/tailscale.conf
        
    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a
        
    - name: Compile the firmware
      id: compile
      if: ${{ inputs.COMPILE }} && !cancelled()
      run: |
        cd openwrt
        make defconfig
        
        echo -e "$(nproc) thread compile"
        
        make package/tailscale/compile V=s -j$(nproc)

        echo "status=success" >> $GITHUB_OUTPUT
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

        find bin/packages/*/packages/ -name "*.ipk"  -exec basename {} \; |sed 's/\.[^.]*$//' > IPK_NAME
        echo "FILE_NAME=_$(cat IPK_NAME)" >> $GITHUB_ENV

    - name: Upload tailscale ipk
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && ${{ inputs.tailscaleBranch }}!= 'none'
      with:
        name: ${{ env.FILE_NAME }}
        path: openwrt/bin/packages/*/packages/tailscale*.ipk

    - name: Clean Compile
      id: clean-compile
      run: |
        cd openwrt
        make clean

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 7
        keep_minimum_runs: 3

    - name: action-bark
      uses: harryzcy/action-bark@v2.0.3
      if: ${{ !cancelled() }}
      with:
        status: ${{ job.status }}
        device_key: ${{ secrets.BARK_DEVICE_KEY }}
        bark_server_url: ${{ secrets.BARK_SERVER_URL }}
